### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by DaveSeidel** [nwhetsell/language-csound#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-dev-edf012e x64
**Electron**: 1.3.14
**OS**: Debian GNU/Linux
**Thrown From**: [language-csound](https://github.com/nwhetsell/language-csound) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At /home/dave/.atom/packages/language-csound/lib/csound-pattern.coffee:54

TypeError: Cannot read property 'push' of undefined
    at CsoundPattern.module.exports.CsoundPattern.handleMatch (/packages/language-csound/lib/csound-pattern.coffee:54:31)
    at Scanner.module.exports.Scanner.handleMatch (/usr/share/atom/resources/app/node_modules/first-mate/lib/scanner.js:69:1)
    at Rule.module.exports.Rule.getNextTags (/usr/share/atom/resources/app/node_modules/first-mate/lib/rule.js:162:1)
    at Grammar.module.exports.Grammar.tokenizeLine (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:152:1)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/usr/share/atom/resources/app/src/tokenized-buffer.js:359:1)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/usr/share/atom/resources/app/src/tokenized-buffer.js:347:1)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app/src/tokenized-buffer.js:203:1)
    at /usr/share/atom/resources/app/src/tokenized-buffer.js:185:1
    at /usr/share/atom/resources/app/node_modules/underscore/underscore.js:666:1
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocomplete-python 1.8.61 
busy-signal 1.3.0 
Hydrogen 1.6.0 
ide-csound 0.0.9 
intentions 1.1.2 
language-csound 0.2.0 
linter 2.1.0 
linter-csound 0.2.4 
linter-python 3.1.1 
linter-ui-default 1.2.1 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
```

**Comment by nwhetsell** [comment]
Without steps to reproduce, I’m afraid there’s little I can do resolve this issue.

**Comment by DaveSeidel** [comment]
All I did was open a CSD file. But I suspect the problem is that (as I just realized) I'm running Atom under the wrong version of node (7.7.3); will fix that with nvm and retry, and then will hopefully be able to close this out.

**Comment by DaveSeidel** [comment]
That was the problem. Sorry about the noise. (BTW, Nate, so you know: the existence of your csound packages are the reason why I've switched to Atom.)

**Comment by nwhetsell** [comment]
No worries!

> the existence of your csound packages are the reason why I've switched to Atom.

Thank you! Whenever real life doesn’t intrude, I’m working on adding type linting to [linter-csound](https://github.com/nwhetsell/linter-csound).

**Comment by eddyc** [comment]
I get the same error on the latest Atom 1.17.0, using node version 6.10.3

**Comment by nwhetsell** [comment]
I’m not able to reproduce this in Atom v1.17.1.

**Comment by nwhetsell** [comment]
Never mind … I can reproduce this.

**Comment by nwhetsell** [comment]
The fundamental issue here comes down code snippets like this:

```csound
opcode aUDO, 0, k
  aUDO kThing
endop
```

There’s no problem with syntax highlighting on GitHub.com, of course. But in Atom, language-csound tries to highlight type sigils (like the `k` in `kThing`) as types. Unfortunately, it’s impossible to highlight type sigils accurately without paying attention to user-defined opcodes (among other things). The `a` in `aUDO` _shouldn’t_ be highlighted as a type sigil.

To accomplish this, language-csound tries to keep track of which opcodes belong to each file. What seems to happening in Atom v1.17 and later is that [`Atom::Workspace::getActiveTextEditor`](https://atom.io/docs/api/v1.17.1/Workspace#instance-getActiveTextEditor) is called slightly later than in Atom v1.16, returning undefined when it used to return a text editor. The result is that language-csound can’t determine which file it’s parsing, and so it can’t determine what opcodes are in files.

About the only thing I can think to do is have language-csound keep track of opcodes in each _workspace_ (window) instead of each file. Does this sound reasonable?

**Comment by eddyc** [comment]
Yeah that sounds fine to me
